#!/usr/bin/env groovy

pipeline {
    agent none
    options {
        timestamps()
    }
    stages {
        stage('Build') {
            steps {
                echo("Building project for ${NAME}.")
                sleep(time:5,unit:'SECONDS')
            }
            post {
                success {
                    echo("Build stage completed with result 'success'.")
                }
                failure {
                    echo("Build stage completed with result 'failure'.")
                }
            }
        }
        stage('Test') {
            steps {
                echo("Testing project for ${NAME}.")
                sleep(time:5,unit:'SECONDS')
            }
            post {
                success {
                    echo("Test stage completed with result 'success'.")
                }
                failure {
                    echo("Test stage completed with result 'failure'.")
                }
            }
        }
        stage('Deploy') {
            steps {
                echo("Deploying project for ${NAME}.")
                sleep(time:5,unit:'SECONDS')
            }
            post {
                success {
                    echo("Deploy stage completed with result 'success'.")
                }
                failure {
                    echo("Deploy stage completed with result 'failure'.")
                }
            }
        }
    }
    post {
        success {
            echo("Pipeline completed for ${NAME} with result 'success'.")
        }
        failure {
            echo("Pipeline completed for ${NAME} with result 'failure'.")
        }
    }
}
